// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminerFieldNames          = builder.RawFieldNames(&Adminer{})
	adminerRows                = strings.Join(adminerFieldNames, ",")
	adminerRowsExpectAutoSet   = strings.Join(stringx.Remove(adminerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminerRowsWithPlaceHolder = strings.Join(stringx.Remove(adminerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminerModel interface {
		Insert(ctx context.Context, data *Adminer) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Adminer, error)
		Update(ctx context.Context, data *Adminer) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Adminer struct {
		Id        int64     `db:"id"`
		Username  string    `db:"username"`
		Password  string    `db:"password"`
		Access    string    `db:"access"`
		IsSuper   int64     `db:"is_super"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newAdminerModel(conn sqlx.SqlConn) *defaultAdminerModel {
	return &defaultAdminerModel{
		conn:  conn,
		table: "`adminer`",
	}
}

func (m *defaultAdminerModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminerModel) FindOne(ctx context.Context, id int64) (*Adminer, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminerRows, m.table)
	var resp Adminer
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminerModel) Insert(ctx context.Context, data *Adminer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, adminerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Access, data.IsSuper)
	return ret, err
}

func (m *defaultAdminerModel) Update(ctx context.Context, data *Adminer) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Access, data.IsSuper, data.Id)
	return err
}

func (m *defaultAdminerModel) tableName() string {
	return m.table
}
