// Code generated by sql2rpc. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
)

type (
	usersmodel interface {
		FindList(ctx context.Context, pageSize, page int64, keyword string, users *Users) (resp []*Users, total int64, err error)
	}
	extendUsersModel struct {
		*defaultUsersModel
	}
)

func newExtendUsersModelModel(defaultUsersModel *defaultUsersModel) *extendUsersModel {
	return &extendUsersModel{
		defaultUsersModel,
	}
}

func (m *extendUsersModel) FindList(ctx context.Context, pageSize, page int64, keyword string, users *Users) (resp []*Users, total int64, err error) {
	hasName := false
	sq := squirrel.Select(usersRows).From(m.table)
	if users != nil {
		if users.Id > 0 {
			sq = sq.Where("id = ?", users.Id)
		}
		if users.ActivityId > 0 {
			sq = sq.Where("activity_id = ?", users.ActivityId)
		}
		if users.AvailableAwards != "" {
			sq = sq.Where("available_awards = ?", users.AvailableAwards)
		}
		if users.Name != "" {
			sq = sq.Where("name = ?", users.Name)
			hasName = true
		}
		if users.Passport != "" {
			sq = sq.Where("passport = ?", users.Passport)
		}
		if users.Count >= 0 {
			sq = sq.Where("count = ?", users.Count)
		}
		if users.Total >= 0 {
			sq = sq.Where("total = ?", users.Total)
		}
	}
	if keyword != "" && !hasName {
		sq = sq.Where("name LIKE ?", fmt.Sprintf("%%%s%%", keyword))
	}
	if pageSize > 0 && page > 0 {
		sqCount := sq.RemoveLimit().RemoveOffset()
		sq = sq.Limit(uint64(pageSize)).Offset(uint64((page - 1) * pageSize))
		queryCount, agrsCount, e := sqCount.ToSql()
		if e != nil {
			err = e
			return
		}
		queryCount = strings.ReplaceAll(queryCount, usersRows, "COUNT(*)")
		if err = m.conn.QueryRowCtx(ctx, &total, queryCount, agrsCount...); err != nil {
			return
		}
	}
	query, agrs, err := sq.ToSql()
	if err != nil {
		return
	}
	resp = make([]*Users, 0)
	if err = m.conn.QueryRowsCtx(ctx, &resp, query, agrs...); err != nil {
		return
	}
	return
}
