version: "3.9"
# 网络配置
networks:
  backend_net:
    driver: bridge
# 数据卷
volumes:
  mysql_volume:
    driver: local

# 服务容器配置
services:
  # app服务
  web:
    build:
      context: .
    hostname: web
    container_name: luckydraw_web
    environment:
      - TZ=Asia/Shanghai
      - GOPROXY=https://goproxy.cn,direct
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USERNAME}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - SERVICE_DEBUG=true
    volumes:
      - .:/app
    ports:
      - 9100:8888
    working_dir: /app
    restart: on-failure
    privileged: true
    stdin_open: true # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend_net
    depends_on:
      - mysql

  #mysql数据库容器
  mysql:
    image: mysql:8.0.32
    container_name: luckydraw_mysql
    hostname: ${MYSQL_HOST}
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USERNAME}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    expose:
      - 3306
    volumes:
      # 数据挂载 - Data mounting
      - mysql_volume:/var/lib/mysql
      # 日志
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: on-failure
    networks:
      - backend_net

  #phpmyadmin
  mysql_manage:
    image: phpmyadmin:latest
    container_name: luckydraw_phpmyadmin
    hostname: phpmyadmin
    restart: on-failure
    ports:
      - 9101:80
    environment:
      - TZ=Asia/Shanghai
      - PMA_ARBITRARY=1 #当设置为 1 连接到任意服务器将被允许
      - PMA_HOST=${MYSQL_HOST} #定义 MySQL 服务器的地址/主机名
      - PMA_PORT=${MYSQL_PORT} # 定义 MySQL 服务器的端口
      - PMA_VERBOSE=luckydraw_mysql # MySQL 服务器的详细名称
      - PMA_PMADB=phpmyadmin # 用于phpMyAdmin 配置存储数据库的数据库名称,如果未设置，则默认情况下不会启用高级功能：用户在使用零配置（零配置）功能登录时仍可能启用这些功能
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_CONTROLUSER=root
      - PMA_CONTROLPASS=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/phpmyadmin/config:/etc/phpmyadmin
      - ./data/phpmyadmin/config/config.inc.php:/etc/phpmyadmin/config.inc.php
    depends_on:
      - mysql
    networks:
      - backend_net
