// Code generated by goctl. DO NOT EDIT.

export interface Enum {
	label: any // 名
	value: any // 值
}

export interface Enums {
	list: Array<Enum> // 枚举列表数据
}

export interface Option {
	title: string // 名
	value: number // 值
}

export interface Options {
	list: Array<Option> // 选项列表数据
}

export interface TreeOption {
	title: string // 名
	value: number // 值
	children?: Array<TreeOption> // 子集
}

export interface TreeOptions {
	list: Array<TreeOption> // 树形选项列表数据
}

export interface JwtToken {
	accessToken: string // token
	accessExpire: number // expire
	refreshAfter: number // refresh at
}

export interface ListReq {
}
export interface ListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
}

export interface ByIdReq {
}
export interface ByIdReqParams {
	id: number // 主键
}

export interface NilReq {
}

export interface NilResp {
}

export interface Resp {
	body: any // 响应数据
}

export interface CaptchaResp {
	captchaId: string // captcha id
	expiresAt: number // expires time
}

export interface BaseResp {
	status: boolean // 响应状态
	success: boolean // 响应状态，用于对接umijs
	message?: string // 给予的提示信息
	data?: any // 【选填】响应的业务数据
	total?: number // 【选填】数据总个数
	pageSize?: number // 【选填】单页数量
	current?: number // 【选填】当前页码，用于对接umijs
	page?: number // 【选填】当前页码
	totalPage?: number // 【选填】自增项，总共有多少页，根据前端的pageSize来计算
	errorCode?: number // 【选填】错误类型代码：400错误请求，401未授权，500服务器内部错误，200成功
	errorMessage?: string // 【选填】向用户显示消息
	traceMessage?: string // 【选填】调试错误信息，请勿在生产环境下使用，可有可无
	showType?: number // 【选填】错误显示类型：0.不提示错误;1.警告信息提示；2.错误信息提示；4.通知提示；9.页面跳转
	traceId?: string // 【选填】方便后端故障排除：唯一的请求ID
	host?: string // 【选填】方便后端故障排除：当前访问服务器的主机
}

export interface CaptchaBgColor {
	R?: number
	G?: number
	B?: number
	A?: number
}

export interface CaptchaReq {
	//Height png height in pixel.
	height?: number
	// Width Captcha png width in pixel.
	width?: number
	//BgColor captcha image background color (optional)
	BgColor: CaptchaBgColor
}

export interface LuckydrawReq {
	passport?: string
	activityUuid?: string
}

export interface CaptchaInfo {
	captchaId: string
	base64Image: string
}

export interface Activity {
	id: number
	uuid: string
	name: string
	status: number
}

export interface AddActivityReq {
	name: string
	status: number
}

export interface PutActivityReq {
	id: number
	uuid: string
	name: string
	status: number
}

export interface DelActivityReq {
	id: number // ID
}

export interface GetActivityReq {
}
export interface GetActivityReqParams {
	id: number // ID
}

export interface GetActivityListReq {
}
export interface GetActivityListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
	id: number
	uuid: string
	name: string
	status: number
}

export interface GetActivityEnumsReq {
}
export interface GetActivityEnumsReqParams {
	parentId: number // 父级ID
}

export interface Adminer {
	id: number
	username: string
	password: string
	access: string
	isSuper: number
}

export interface AddAdminerReq {
	username: string
	password: string
	access: string
	isSuper: number
}

export interface PutAdminerReq {
	id: number
	username: string
	password: string
	access: string
	isSuper: number
}

export interface DelAdminerReq {
	id: number // ID
}

export interface GetAdminerReq {
}
export interface GetAdminerReqParams {
	id: number // ID
}

export interface GetAdminerListReq {
}
export interface GetAdminerListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
	id: number
	username: string
	password: string
	access: string
	isSuper: number
}

export interface GetAdminerEnumsReq {
}
export interface GetAdminerEnumsReqParams {
	parentId: number // 父级ID
}

export interface AdminerLoginReq {
	username: string
	password: string
	autoLogin: boolean
	captchaId: string
	solution: string
}

export interface Awards {
	id: number
	activityId: number
	uuid: string
	grade: string
	name: string
	image: string
	price: number // 奖品价格
	prob: number
	quantity: number // 总数量
	count: number // 已抽数量
	isWin: number // 是否中奖
}

export interface AddAwardsReq {
	activityId: number
	grade: string
	name: string
	image: string
	price: number // 奖品价格
	prob: number
	quantity: number // 总数量
	count: number // 已抽数量
	isWin: number // 是否中奖
}

export interface PutAwardsReq {
	id: number
	activityId: number
	uuid: string
	grade: string
	name: string
	image: string
	price: number // 奖品价格
	prob: number
	quantity: number // 总数量
	count: number // 已抽数量
	isWin: number // 是否中奖
}

export interface DelAwardsReq {
	id: number // ID
}

export interface GetAwardsReq {
}
export interface GetAwardsReqParams {
	id: number // ID
}

export interface GetAwardsListReq {
}
export interface GetAwardsListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
	id: number
	activityId: number
	uuid: string
	grade: string
	name: string
	image: string
	price: number // 奖品价格
	prob: number
	quantity: number // 总数量
	count: number // 已抽数量
	isWin: number // 是否中奖
}

export interface GetAwardsEnumsReq {
}
export interface GetAwardsEnumsReqParams {
	parentId: number // 父级ID
}

export interface GetAwardsListByActivityUuidReq {
	activityUuid: string
}

export interface PublicAwards {
	id: number
	uuid: string
	grade: string
	name: string
	image: string
	price: number
	is_win: boolean
}

export interface SelectAwardsByIdsReq {
	ids: Array<number>
}

export interface Users {
	id: number
	activityId: number
	availableAwards: string // 指定其可抽中的奖品
	name: string
	passport: string
	count: number // 抽獎次數
	total: number
}

export interface AddUsersReq {
	activityId: number
	availableAwards: string // 指定其可抽中的奖品
	name: string
	passport: string
	count: number // 抽獎次數
	total: number
}

export interface PutUsersReq {
	id: number
	activityId: number
	availableAwards: string // 指定其可抽中的奖品
	name: string
	passport: string
	count: number // 抽獎次數
	total: number
}

export interface DelUsersReq {
	id: number // ID
}

export interface GetUsersReq {
}
export interface GetUsersReqParams {
	id: number // ID
}

export interface GetUsersListReq {
}
export interface GetUsersListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
	id: number
	activityId: number
	availableAwards: string // 指定其可抽中的奖品
	name: string
	passport: string
	count: number // 抽獎次數
	total: number
}

export interface GetUsersEnumsReq {
}
export interface GetUsersEnumsReqParams {
	parentId: number // 父级ID
}

export interface UserRegisterReq {
	userPassport: string // 用户凭证
	activityUuid: string // 活动凭证
	secretKey: string // 密钥
}

export interface UserLoginReq {
	passport: string // 用户凭证
	activityUuid: string // 活动凭证
}

export interface PublicUser {
	id: number
	activity_id: number
	passport: string
	count: number // 抽獎次數
	total: number
}

export interface CurrentUserReq {
	passport?: string
	activityUuid?: string
}

export interface UserDetail {
	user?: Users
	activity?: Activity
	availableAwards?: Array<Awards>
}

export interface WinningRecords {
	id: number
	userId: number
	awardId: number
	activityId: number
	ip: string
	platform: string
}

export interface AddWinningRecordsReq {
	userId: number
	awardId: number
	activityId: number
	ip: string
	platform: string
}

export interface PutWinningRecordsReq {
	id: number
	userId: number
	awardId: number
	activityId: number
	ip: string
	platform: string
}

export interface DelWinningRecordsReq {
	id: number // ID
}

export interface GetWinningRecordsReq {
}
export interface GetWinningRecordsReqParams {
	id: number // ID
}

export interface GetWinningRecordsListReq {
}
export interface GetWinningRecordsListReqParams {
	pageSize: number // 页面容量，默认20，可选
	page: number // 当前页码，默认1，可选
	current: number // 当前页码，默认1，用于对接umijs，可选
	keyword: string // 关键词，可选
	id: number
	userId: number
	awardId: number
	activityId: number
	ip: string
	platform: string
}

export interface GetWinningRecordsEnumsReq {
}
export interface GetWinningRecordsEnumsReqParams {
	parentId: number // 父级ID
}

export interface QueryReq {
	passport?: string
	activityUuid?: string
}

export interface WinningRecordsInfo {
	winningRecord?: WinningRecords
	award?: PublicAwards
}

export interface WinningRecordsDetail {
	winningRecord?: WinningRecords
	award?: Awards
	user?: Users
	activity?: Activity
}

